model_params:
  name: 'VanillaVAEUNet'
  in_channels: 3
  latent_dim: 128
  hidden_dims: [32, 64, 128, 256, 256, 512]

exp_params:
  dataset: concrete-cracks
  data_path: "/cvhci/data/construction/Concrete-Cracks"
  img_size: 128
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [3]
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "VanillaVAEUNet"
  manual_seed: 42
